common/models/Shops.php
<?php

namespace common\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yiidreamteam\upload\ImageUploadBehavior;

/**
 * This is the model class for table "shops".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $description
 * @property string|null $latitude
 * @property string|null $longitude
 * @property string|null $logo
 * @property string|null $created_at
 * @property string|null $updated_at
 */
class Shops extends ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'shops';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at']
                ],
                // если вместо метки времени UNIX используется datetime:
                'value' => date('Y-m-d H:i:s')
            ],
            [
                'class' => ImageUploadBehavior::class,
                'attribute' => 'logo',
                'filePath' => '@storage/data/shop-image/[[attribute_id]]/[[filename]].[[extension]]',
                'fileUrl' => '/uploads/storage/data/shop-image/[[attribute_id]]/[[filename]].[[extension]]'
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'description', 'longitude', 'latitude', 'logo'], 'required'],
            [['description'], 'string'],
            [['logo'], 'file', 'maxSize' => 1024 * 1024 * 1, 'tooBig' => 'Файл не должен превышать 1 мб'],
            [['longitude', 'latitude'], 'string'],
            [['created_at', 'updated_at', 'location', 'logo'], 'safe'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Дўкон номи',
            'description' => 'Дўкон тавсифи',
            'location' => 'Дўкон манзили',
            'logo' => 'Дўкон расми',
            'created_at' => 'Қўшилган вақти',
            'updated_at' => 'Ўзгартирилган вақти',
            'longitude' => 'Узунлик(longitude)',
            'latitude' => 'Кенглик(latitude)',
        ];
    }

    public function getProducts()
    {
        return $this->hasMany(Products::className(), ['shop_id' => 'id']);
    }

    public function getFileUrl()
    {
        return $this->getUploadedFileUrl('logo');
    }
}

backend/controllers/ShopProductsController.php
<?php

namespace backend\controllers;

use common\models\ShopProducts;
use common\models\search_models\ShopProductsSearch;
use common\models\Shops;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ShopProductsController implements the CRUD actions for ShopProducts model.
 */
class ShopProductsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all ShopProducts models.
     *
     * @return string
     */
    public function actionIndex($shop_id)
    {
        $searchModel = new ShopProductsSearch();
        $searchModel->shop_id = $shop_id;
        $dataProvider = $searchModel->search($this->request->queryParams);

        $shop = $this->findShopModel($shop_id);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'shop' => $shop
        ]);
    }

    /**
     * Displays a single ShopProducts model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'shop' => $this->findShopModel($this->findModel($id)->shop_id)
        ]);
    }

    /**
     * Creates a new ShopProducts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($shop_id)
    {
        $shop = $this->findShopModel($shop_id);
        $model = new ShopProducts();
        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                if ($model->products) {
                    foreach ($model->products as $product_id) {
                        $shopProductModel = new ShopProducts();
                        if (ShopProducts::find()->where(['shop_id' => $shop_id, 'product_id' => $product_id])->exists()) {
                            continue;
                        } else {
                            $shopProductModel->shop_id = $shop_id;
                            $shopProductModel->product_id = $product_id;
                            $shopProductModel->save();
                        }

                    }
                }
                return $this->redirect(['index', 'shop_id' => $shop_id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'shop' => $shop
        ]);
    }

    /**
     * Updates an existing ShopProducts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ShopProducts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();

        return $this->redirect(['index', 'shop_id' => $model->shop_id]);
    }

    /**
     * Finds the ShopProducts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return ShopProducts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ShopProducts::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Маълумотлар топилмади!');
    }

    protected function findShopModel($id)
    {
        if (($model = Shops::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Дўкон мавжуд эмас!');
    }
}

backend/controllers/ShopsController.php
<?php

namespace backend\controllers;

use common\models\Shops;
use common\models\search_models\ShopsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ShopsController implements the CRUD actions for Shops model.
 */
class ShopsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Shops models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ShopsSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Shops model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Shops model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Shops();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Shops model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Shops model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Shops model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Shops the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Shops::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/shops/_form.php
<?php

use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Shops */
/* @var $form yii\widgets\ActiveForm */
?>
<link rel="stylesheet" href="/leaflet/leaflet.css"/>
<script src="/leaflet/leaflet.js"></script>


<div class="shops-form">

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'options' => [
            'enctype' => 'multipart/form-data',
        ],
    ]); ?>
    <?= $form->field($model, 'longitude')->hiddenInput(['maxlength' => true, 'id' => 'longitude'])->label(false) ?>
    <?= $form->field($model, 'latitude')->hiddenInput(['maxlength' => true, 'id' => 'latitude'])->label(false) ?>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-md-12">
            <div id="map" style="width:100%; height:350px"></div>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'logo')->widget(FileInput::class, [
                'options' => ['accept' => 'image/*'],
                'language' => Yii::$app->language,
                'pluginOptions' => [
                    'showPreview' => true,
                    'showCaption' => false,
                    'showRemove' => false,
                    'showCancel' => false,
                    'showUpload' => false,
                    'previewFileType' => 'any',
                    'browseClass' => 'btn btn-primary btn-block',
                    'browseLabel' => 'Юклаш',
                    'layoutTemplates' => [
                        'main1' => '<div class="kv-upload-progress hide"></div>{browse}{preview}',
                    ],
                    'initialPreview' => [
                        Html::a($model->logo, $model->getUploadedFileUrl('logo'), ['target' => '_blank'])
                    ],
                ],
            ]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'description')->textarea(['maxlength' => true]) ?>
        </div>
    </div>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<script>
    var center = ['41.315456', '69.274975'];
    if (<?= !$model->isNewRecord ? 'true' : 'false' ?>) {
        center = ['<?= $model->latitude ?>', '<?= $model->longitude ?>'];
    }
    var mapOptions = {
        center: center,
        zoom: 15
    }
    // Creating a map object
    var map = new L.map('map', mapOptions);

    // Creating a Layer object
    var layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');

    // Adding layer to the map
    map.addLayer(layer);

    if (<?= !$model->isNewRecord ? 'true' : 'false' ?>) {
        // Creating a marker
        var marker = L.marker(['<?= $model->latitude ?>', '<?= $model->longitude ?>']);

        // Adding marker to the map
        marker.addTo(map);
    }


    var long = document.getElementById('longitude')
    var lat = document.getElementById('latitude')

    var popup = L.popup();

    function onMapClick(e) {
        long.value = e.latlng.lng
        lat.value = e.latlng.lat
        popup
            .setLatLng(e.latlng)
            .setContent("Жойлашув белгиланди")
            .openOn(map);
    }

    map.on('click', onMapClick);
</script>

backend/views/shops/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search_models\ShopsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shops-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'location') ?>

    <?= $form->field($model, 'logo') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/shops/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Shops */

$this->title = 'Янги қўшиш';
$this->params['breadcrumbs'][] = ['label' => 'Дўконлар', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categories-create">

    <div class="card">
        <div class="card-body">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>

backend/views/shops/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search_models\ShopsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Дўконлар';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shops-index">

    <p>
        <?= Html::a('Янги қўшиш', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => [
            'class' => 'dataTables_wrapper dt-bootstrap4',
        ],
        'tableOptions' => [
            'class' => 'table table-bordered table-hover dataTable dtr-inline',
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'id',
            'name',
            'description:ntext',
//            'location',
            [
                'attribute' => 'logo',
                'value' => function ($model) {
                    return $model->logo ? Html::img($model->fileUrl, ['download' => true,'style' => ['width' => '200px']]) : '--';
                },
                'format' => 'raw',
                'filter' => false,
            ],
            [
                'class' => ActionColumn::className(),
                'template' => '{view} {update} {delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="btn btn-info"><i class="fas fa-eye"></i></span>', $url, [
                            'title' => 'Дўконни кўриш',
                        ]);
                    },
                    'update' => function ($url, $model) {
                        return Html::a('<span class="btn btn-primary"><i class="fas fa-pencil"></i></span>', $url, [
                            'title' => 'Дўконни таҳрирлаш',
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="btn btn-danger"><i class="fas fa-trash"></i></span>', $url, [
                            'title' => 'Дўконни ўчириш',
                            'data-confirm' => Yii::t('yii', 'Are you sure to delete this item?'),
                            'data-method' => 'post',
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>


</div>

backend/views/shops/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Shops */

$this->title = 'Таҳрирлаш: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Дўконлар', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Таҳрирлаш';
?>
<div class="categories-create">

    <div class="card">
        <div class="card-body">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>

</div>

backend/views/shops/view.php
<?php

use yii\helpers\Html;
use yii\web\YiiAsset;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Shops */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Дўконлар', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>
<link rel="stylesheet" href="/leaflet/leaflet.css"/>
<script src="/leaflet/leaflet.js"></script>

<div>
    <p>
        <?= Html::a('Таҳрирлаш', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Дўконда мавжуд махсулотлар', ['/shop-products/index', 'shop_id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?= Html::a('Ўчириш', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'id',
            'name',
            'description:ntext',
            [
                'attribute' => 'location',
                'value' => function ($model) {
                    return '<div id="map" style="width:100%; height:350px"></div>';
                },
                'format' => 'raw',
                'visible' => $model->longitude ? true : false,
            ],
            [
                'attribute' => 'logo',
                'value' => function ($model) {
                    return $model->logo ? Html::img($model->fileUrl, ['download' => true, 'style' => ['width' => '600px']]) : '--';
                },
                'format' => 'raw'
            ],
            'created_at:datetime',
            'updated_at:datetime',
        ]
    ]); ?>
</div>


<script>
    if (<?= $model->latitude ? 'true' : 'false' ?>) {
        var mapOptions = {
            center: [<?= $model->latitude ?>, <?= $model->longitude ?>],
            zoom: 18
        }
        var map = new L.map('map', mapOptions);

        var layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');

        map.addLayer(layer);

        var marker = L.marker([<?= $model->latitude  ?>, <?= $model->longitude ?>]);

        marker.addTo(map);
    }
</script>